[package]
name = "typaxis-font"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
read-fonts = { version = "=0.31.3", default-features = false, features = ["std"] }
typaxis-core = { path = "../typaxis-core" }
