#![forbid(unsafe_code)]

use typaxis_core::{
    AdmittedResourceFingerprint, DocumentFingerprint, FontFaceId, FontInstanceId,
    GeneratedBufferKey, GenerationKind, NodeId, ReferenceFingerprint, StyleFingerprint, TextSpan,
    Utf8ByteOffset,
};
use typaxis_resource_admission::{
    AdmittedFontInstanceRef, AdmittedFontInstanceTable, AdmittedResourceLedgerToken,
    ResourceAdmissionError,
};
use typaxis_style::{ResolvedTextStyle, StyleValidationError};
use typaxis_syntax::{
    PackageComputedStyle, PackageGeneratedTextBinding, PackageParagraphTextSite,
    PackageShapeTextError, PackageStyleError, ValidatedMachinePackage, ValidatedParsedPackage,
};

/// Exact identity of all validated inputs that can affect one layout state.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct LayoutEpoch {
    document: DocumentFingerprint,
    style: StyleFingerprint,
    admitted_resources: AdmittedResourceFingerprint,
    references: ReferenceFingerprint,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum LayoutEpochError {
    AdmittedResourceDocumentMismatch,
    PackageEpochMismatch,
}

impl LayoutEpoch {
    pub fn from_validated_inputs(
        generated_text: PackageGeneratedTextBinding<'_>,
        admitted_resources: AdmittedResourceLedgerToken<'_>,
    ) -> Result<Self, LayoutEpochError> {
        let package = generated_text.package();
        if !admitted_resources
            .ledger()
            .matches_declarations(&package.package().resources)
        {
            return Err(LayoutEpochError::AdmittedResourceDocumentMismatch);
        }
        Ok(Self {
            document: package.epoch_identity().document(),
            style: package.epoch_identity().style(),
            admitted_resources: admitted_resources.fingerprint(),
            references: generated_text.generated_text().reference_fingerprint(),
        })
    }

    pub const fn document(self) -> DocumentFingerprint {
        self.document
    }
    pub const fn style(self) -> StyleFingerprint {
        self.style
    }
    pub const fn admitted_resources(self) -> AdmittedResourceFingerprint {
        self.admitted_resources
    }
    pub const fn references(self) -> ReferenceFingerprint {
        self.references
    }

    /// Reissues the epoch for the next pagination pass while preserving the
    /// stable document, style, and admitted-resource identities. The new
    /// reference identity is accepted only from the package-owned generated
    /// text validation boundary.
    pub fn with_generated_text(
        self,
        generated_text: PackageGeneratedTextBinding<'_>,
    ) -> Result<Self, LayoutEpochError> {
        let package = generated_text.package();
        if self.document != package.epoch_identity().document()
            || self.style != package.epoch_identity().style()
        {
            return Err(LayoutEpochError::PackageEpochMismatch);
        }
        Ok(Self {
            document: self.document,
            style: self.style,
            admitted_resources: self.admitted_resources,
            references: generated_text.generated_text().reference_fingerprint(),
        })
    }

    /// Returns whether two states share every pagination input other than the
    /// generated reference overlay.
    pub fn same_stable_inputs(self, other: Self) -> bool {
        self.document == other.document
            && self.style == other.style
            && self.admitted_resources == other.admitted_resources
    }
}

/// Stable identity of one parsed or generated text-producing package site.
///
/// The generated variant deliberately stores the allocation-independent key,
/// not a generated text-buffer ID. Pagination may replace generated bytes and
/// IDs while the logical site and its computed style remain unchanged.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum MachineTextSiteSource {
    Parsed(TextSpan),
    Generated(GeneratedBufferKey),
}

/// `check-package` resolves families and binds font instances, but glyph
/// coverage remains a shaping-time property of the final generated text.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum MachineGlyphCoverage {
    DeferredToBuildShaping,
}

/// One canonically ordered text-site result from machine style/font coverage.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PreparedMachineTextSite {
    source: MachineTextSiteSource,
    site_owner: NodeId,
    style_owner: NodeId,
    computed: PackageComputedStyle,
    resolved: ResolvedLayoutTextStyle,
    font_instance_id: FontInstanceId,
}

impl PreparedMachineTextSite {
    pub const fn source(&self) -> MachineTextSiteSource {
        self.source
    }

    pub const fn site_owner(&self) -> NodeId {
        self.site_owner
    }

    pub const fn style_owner(&self) -> NodeId {
        self.style_owner
    }

    pub const fn computed(&self) -> &PackageComputedStyle {
        &self.computed
    }

    pub const fn resolved(&self) -> &ResolvedLayoutTextStyle {
        &self.resolved
    }

    pub const fn font_instance_id(&self) -> FontInstanceId {
        self.font_instance_id
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum MachineStyleFontPreparationError {
    LayoutEpoch(LayoutEpochError),
    ParsedText(PackageShapeTextError),
    GeneratedText(PackageShapeTextError),
    MissingGeneratedBuffer(GeneratedBufferKey),
    GeneratedTextTooLarge(GeneratedBufferKey),
    InvalidGeneratedProvenance(GeneratedBufferKey),
    Style(PackageStyleError),
    LayoutStyle(LayoutTextStyleError),
    Resource(ResourceAdmissionError),
    FontSelection(ShapeFontSelectionError),
    ResourceLimit,
}

/// Complete style-family/font-instance coverage proof for a machine package.
///
/// Construction walks paragraph/heading sites in typed NodeId preorder, then
/// checks every remaining generated site. Discretionary break-control sites
/// are recorded separately because they cannot produce glyphs and therefore
/// need no family. The proof owns the dense font-instance table used by
/// layout, so downstream shaping cannot replace a resolved family with a
/// caller-selected face.
#[derive(Debug)]
pub struct PreparedMachineStyleFonts {
    epoch: LayoutEpoch,
    sites: Vec<PreparedMachineTextSite>,
    non_text_generated_sites: Vec<GeneratedBufferKey>,
    font_instances: AdmittedFontInstanceTable,
    glyph_coverage: MachineGlyphCoverage,
}

impl PreparedMachineStyleFonts {
    pub fn prepare(
        package: &ValidatedMachinePackage,
        generated: PackageGeneratedTextBinding<'_>,
        admitted: AdmittedResourceLedgerToken<'_>,
    ) -> Result<Self, MachineStyleFontPreparationError> {
        let parsed = package.package();
        if !core::ptr::eq(generated.package(), parsed) {
            return Err(MachineStyleFontPreparationError::LayoutEpoch(
                LayoutEpochError::PackageEpochMismatch,
            ));
        }
        let epoch = LayoutEpoch::from_validated_inputs(generated, admitted)
            .map_err(MachineStyleFontPreparationError::LayoutEpoch)?;

        let node_count = parsed.document_nodes().node_count();
        let generated_count = parsed.document_nodes().generated_sites().len();
        let capacity = node_count
            .checked_add(generated_count)
            .ok_or(MachineStyleFontPreparationError::ResourceLimit)?;
        let mut sources = Vec::new();
        sources
            .try_reserve_exact(capacity)
            .map_err(|_| MachineStyleFontPreparationError::ResourceLimit)?;
        let mut seen_generated = std::collections::BTreeSet::new();
        let mut non_text_generated_sites = Vec::new();
        non_text_generated_sites
            .try_reserve_exact(generated_count)
            .map_err(|_| MachineStyleFontPreparationError::ResourceLimit)?;

        for (owner, _kind) in parsed.document_nodes().nodes() {
            let Some(paragraph_sites) = parsed.paragraph_shape_text_sites(owner) else {
                continue;
            };
            for site in paragraph_sites {
                match site {
                    PackageParagraphTextSite::Parsed(span) => {
                        sources.push(MachineTextSiteSource::Parsed(span));
                    }
                    PackageParagraphTextSite::Generated(key) => {
                        seen_generated.insert(key);
                        sources.push(MachineTextSiteSource::Generated(key));
                    }
                }
            }
        }

        // Discretionary sites represent explicit line-break control and never
        // require a font. They are still bound against the selected generated
        // store so the coverage proof closes over the complete site registry.
        // Every other generated site can materialize text in a later
        // pagination state and therefore participates in family binding.
        for site in parsed.document_nodes().generated_sites() {
            let key = site.key();
            if !seen_generated.insert(key) {
                continue;
            }
            if key.generation_kind() == GenerationKind::Discretionary {
                let buffer = generated
                    .generated_text()
                    .buffers()
                    .iter()
                    .find(|buffer| buffer.key() == key)
                    .ok_or(MachineStyleFontPreparationError::MissingGeneratedBuffer(
                        key,
                    ))?;
                let end = u32::try_from(buffer.utf8().len())
                    .map_err(|_| MachineStyleFontPreparationError::GeneratedTextTooLarge(key))?;
                let provenance = generated
                    .generated_text()
                    .provenance(key, Utf8ByteOffset::new(0), Utf8ByteOffset::new(end))
                    .map_err(|_| {
                        MachineStyleFontPreparationError::InvalidGeneratedProvenance(key)
                    })?;
                generated
                    .bind_generated_shape_text(provenance)
                    .map_err(MachineStyleFontPreparationError::GeneratedText)?;
                non_text_generated_sites.push(key);
            } else {
                sources.push(MachineTextSiteSource::Generated(key));
            }
        }

        let mut drafts = Vec::new();
        drafts
            .try_reserve_exact(sources.len())
            .map_err(|_| MachineStyleFontPreparationError::ResourceLimit)?;
        for source in sources {
            let text = match source {
                MachineTextSiteSource::Parsed(span) => parsed
                    .bind_parsed_shape_text(span)
                    .map_err(MachineStyleFontPreparationError::ParsedText)?,
                MachineTextSiteSource::Generated(key) => {
                    let buffer = generated
                        .generated_text()
                        .buffers()
                        .iter()
                        .find(|buffer| buffer.key() == key)
                        .ok_or(MachineStyleFontPreparationError::MissingGeneratedBuffer(
                            key,
                        ))?;
                    let end = u32::try_from(buffer.utf8().len()).map_err(|_| {
                        MachineStyleFontPreparationError::GeneratedTextTooLarge(key)
                    })?;
                    let provenance = generated
                        .generated_text()
                        .provenance(key, Utf8ByteOffset::new(0), Utf8ByteOffset::new(end))
                        .map_err(|_| {
                            MachineStyleFontPreparationError::InvalidGeneratedProvenance(key)
                        })?;
                    generated
                        .bind_generated_shape_text(provenance)
                        .map_err(MachineStyleFontPreparationError::GeneratedText)?
                }
            };
            let computed = parsed
                .cascade_style(text.site_owner())
                .map_err(MachineStyleFontPreparationError::Style)?;
            let resolved = ResolvedLayoutTextStyle::new(parsed, &computed, admitted)
                .map_err(MachineStyleFontPreparationError::LayoutStyle)?;
            drafts.push((
                source,
                text.site_owner(),
                text.style_owner(),
                computed,
                resolved,
            ));
        }

        let font_instances = AdmittedFontInstanceTable::from_used_faces(
            admitted.ledger(),
            drafts
                .iter()
                .map(|(_, _, _, _, resolved)| resolved.resolved().font_face_id()),
        )
        .map_err(MachineStyleFontPreparationError::Resource)?;
        let mut sites = Vec::new();
        sites
            .try_reserve_exact(drafts.len())
            .map_err(|_| MachineStyleFontPreparationError::ResourceLimit)?;
        for (source, site_owner, style_owner, computed, resolved) in drafts {
            let selection =
                ShapeFontSelectionReceipt::new(parsed, &computed, admitted, &font_instances, epoch)
                    .map_err(MachineStyleFontPreparationError::FontSelection)?;
            sites.push(PreparedMachineTextSite {
                source,
                site_owner,
                style_owner,
                computed,
                resolved,
                font_instance_id: selection.admitted_font().font_instance_id(),
            });
        }
        sites.sort_by_key(machine_site_order_key);

        Ok(Self {
            epoch,
            sites,
            non_text_generated_sites,
            font_instances,
            glyph_coverage: MachineGlyphCoverage::DeferredToBuildShaping,
        })
    }

    pub const fn epoch(&self) -> LayoutEpoch {
        self.epoch
    }

    pub fn sites(&self) -> &[PreparedMachineTextSite] {
        &self.sites
    }

    pub fn non_text_generated_sites(&self) -> &[GeneratedBufferKey] {
        &self.non_text_generated_sites
    }

    pub const fn font_instances(&self) -> &AdmittedFontInstanceTable {
        &self.font_instances
    }

    pub const fn glyph_coverage(&self) -> MachineGlyphCoverage {
        self.glyph_coverage
    }

    pub fn site(
        &self,
        source: MachineTextSiteSource,
        site_owner: NodeId,
    ) -> Option<&PreparedMachineTextSite> {
        self.sites
            .iter()
            .find(|site| site.source == source && site.site_owner == site_owner)
    }

    pub fn matches_package_epoch(
        &self,
        package: &ValidatedMachinePackage,
        epoch: LayoutEpoch,
    ) -> bool {
        let identity = package.package().epoch_identity();
        self.epoch.same_stable_inputs(epoch)
            && self.epoch.document() == identity.document()
            && self.epoch.style() == identity.style()
    }
}

fn machine_site_order_key(site: &PreparedMachineTextSite) -> (u32, u8, u32, u32, u32) {
    match site.source {
        MachineTextSiteSource::Parsed(span) => (
            site.site_owner.get(),
            0,
            span.text_id().get(),
            span.start_byte().get(),
            span.end_byte().get(),
        ),
        MachineTextSiteSource::Generated(key) => (
            site.site_owner.get(),
            1,
            key.owner().get(),
            machine_generation_kind_order(key.generation_kind()),
            key.owner_local_ordinal(),
        ),
    }
}

const fn machine_generation_kind_order(kind: GenerationKind) -> u32 {
    match kind {
        GenerationKind::PageReference => 0,
        GenerationKind::Counter => 1,
        GenerationKind::ListMarker => 2,
        GenerationKind::FootnoteMarker => 3,
        GenerationKind::Discretionary => 4,
    }
}

/// Text style after package/style identity and the admitted resource set have
/// all been checked at one trust boundary.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ResolvedLayoutTextStyle {
    owner: NodeId,
    style_owner: NodeId,
    document: DocumentFingerprint,
    style: StyleFingerprint,
    admitted_resources: AdmittedResourceFingerprint,
    resolved: ResolvedTextStyle,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum LayoutTextStyleError {
    PackageStyleMismatch,
    AdmittedResourceDocumentMismatch,
    InvalidStyle(StyleValidationError),
}

impl ResolvedLayoutTextStyle {
    pub fn new(
        package: &ValidatedParsedPackage,
        computed: &PackageComputedStyle,
        admitted: AdmittedResourceLedgerToken<'_>,
    ) -> Result<Self, LayoutTextStyleError> {
        if computed.document_fingerprint() != package.epoch_identity().document()
            || computed.style_fingerprint() != package.epoch_identity().style()
        {
            return Err(LayoutTextStyleError::PackageStyleMismatch);
        }
        if !admitted
            .ledger()
            .matches_declarations(&package.package().resources)
        {
            return Err(LayoutTextStyleError::AdmittedResourceDocumentMismatch);
        }
        let resolved = ResolvedTextStyle::try_from_computed(computed.computed(), admitted)
            .map_err(LayoutTextStyleError::InvalidStyle)?;
        Ok(Self {
            owner: computed.owner(),
            style_owner: computed.style_owner(),
            document: computed.document_fingerprint(),
            style: computed.style_fingerprint(),
            admitted_resources: admitted.fingerprint(),
            resolved,
        })
    }

    pub const fn owner(&self) -> NodeId {
        self.owner
    }
    pub const fn style_owner(&self) -> NodeId {
        self.style_owner
    }
    pub const fn document_fingerprint(&self) -> DocumentFingerprint {
        self.document
    }
    pub const fn style_fingerprint(&self) -> StyleFingerprint {
        self.style
    }
    pub const fn admitted_resource_fingerprint(&self) -> AdmittedResourceFingerprint {
        self.admitted_resources
    }
    pub fn matches_epoch(&self, epoch: LayoutEpoch) -> bool {
        self.document == epoch.document()
            && self.style == epoch.style()
            && self.admitted_resources == epoch.admitted_resources()
    }
    pub const fn resolved(&self) -> &ResolvedTextStyle {
        &self.resolved
    }
}

/// Sealed selection proof consumed by shaping. It is impossible to construct
/// this receipt from a caller-selected instance ID, hash, or raw font bytes.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ShapeFontSelectionReceipt<'a> {
    epoch: LayoutEpoch,
    style: ResolvedLayoutTextStyle,
    font: AdmittedFontInstanceRef<'a>,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ShapeFontSelectionError {
    LayoutStyle(LayoutTextStyleError),
    EpochMismatch,
    FontInstanceLedgerMismatch,
    MissingFontInstance(FontFaceId),
    DuplicateFontFaceInstance(FontFaceId),
}

impl<'a> ShapeFontSelectionReceipt<'a> {
    pub fn new(
        package: &ValidatedParsedPackage,
        computed: &PackageComputedStyle,
        admitted: AdmittedResourceLedgerToken<'a>,
        instances: &'a AdmittedFontInstanceTable,
        epoch: LayoutEpoch,
    ) -> Result<Self, ShapeFontSelectionError> {
        let style = ResolvedLayoutTextStyle::new(package, computed, admitted)
            .map_err(ShapeFontSelectionError::LayoutStyle)?;
        if !style.matches_epoch(epoch) {
            return Err(ShapeFontSelectionError::EpochMismatch);
        }
        let selected_face = style.resolved().font_face_id();
        let font_instance_id = select_font_instance(
            admitted.fingerprint(),
            instances.ledger_fingerprint(),
            selected_face,
            instances
                .instances()
                .iter()
                .map(|instance| (instance.font_instance_id(), instance.font_face_id())),
        )?;
        let font = instances
            .resolve(font_instance_id, admitted.ledger())
            .ok_or(ShapeFontSelectionError::FontInstanceLedgerMismatch)?;
        if font.ledger_fingerprint() != admitted.fingerprint()
            || font.font_face_id() != selected_face
        {
            return Err(ShapeFontSelectionError::FontInstanceLedgerMismatch);
        }
        Ok(Self { epoch, style, font })
    }

    pub const fn epoch(&self) -> LayoutEpoch {
        self.epoch
    }
    pub const fn style(&self) -> &ResolvedLayoutTextStyle {
        &self.style
    }
    pub const fn owner(&self) -> NodeId {
        self.style.style_owner()
    }
    pub const fn admitted_font(&self) -> AdmittedFontInstanceRef<'a> {
        self.font
    }
    pub fn matches_epoch(&self, epoch: LayoutEpoch) -> bool {
        self.epoch == epoch
    }
}

fn select_font_instance(
    expected_ledger: AdmittedResourceFingerprint,
    table_ledger: AdmittedResourceFingerprint,
    selected_face: FontFaceId,
    instances: impl IntoIterator<Item = (FontInstanceId, FontFaceId)>,
) -> Result<FontInstanceId, ShapeFontSelectionError> {
    if table_ledger != expected_ledger {
        return Err(ShapeFontSelectionError::FontInstanceLedgerMismatch);
    }
    let mut matching = instances
        .into_iter()
        .filter(|(_, face)| *face == selected_face);
    let selected = matching
        .next()
        .ok_or(ShapeFontSelectionError::MissingFontInstance(selected_face))?;
    if matching.next().is_some() {
        return Err(ShapeFontSelectionError::DuplicateFontFaceInstance(
            selected_face,
        ));
    }
    Ok(selected.0)
}

#[cfg(test)]
mod tests {
    use super::*;
    use typaxis_core::admitted_resource_fingerprint_from_jcs;

    #[test]
    fn font_selection_rejects_a_table_from_another_ledger() {
        let expected = admitted_resource_fingerprint_from_jcs("{\"ledger\":0}");
        let other = admitted_resource_fingerprint_from_jcs("{\"ledger\":1}");
        assert_eq!(
            select_font_instance(
                expected,
                other,
                FontFaceId::new(0),
                [(FontInstanceId::new(0), FontFaceId::new(0))],
            ),
            Err(ShapeFontSelectionError::FontInstanceLedgerMismatch)
        );
    }

    #[test]
    fn font_selection_rejects_wrong_or_duplicate_faces() {
        let ledger = admitted_resource_fingerprint_from_jcs("{\"ledger\":0}");
        assert_eq!(
            select_font_instance(
                ledger,
                ledger,
                FontFaceId::new(0),
                [(FontInstanceId::new(0), FontFaceId::new(1))],
            ),
            Err(ShapeFontSelectionError::MissingFontInstance(
                FontFaceId::new(0)
            ))
        );
        assert_eq!(
            select_font_instance(
                ledger,
                ledger,
                FontFaceId::new(0),
                [
                    (FontInstanceId::new(0), FontFaceId::new(0)),
                    (FontInstanceId::new(1), FontFaceId::new(0)),
                ],
            ),
            Err(ShapeFontSelectionError::DuplicateFontFaceInstance(
                FontFaceId::new(0)
            ))
        );
    }
}
