[package]
name = "typaxis-pdf"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
typaxis-core = { path = "../typaxis-core" }
typaxis-display-list = { path = "../typaxis-display-list" }
typaxis-resources = { path = "../typaxis-resources" }
typaxis-syntax = { path = "../typaxis-syntax" }

[dev-dependencies]
typaxis-display-list = { path = "../typaxis-display-list", features = ["staging-fixtures"] }
