#!/usr/bin/env python3
"""Independently join each scale-probe source occurrence to PDF paint and tags.

Requires the package generated by prepare_vmb_distinct_probe.py. This does not
establish full-book convergence, final body shaping or publication typography.
"""
import argparse
import hashlib
import json
import subprocess
from pathlib import Path
from pypdf import PdfReader
from pypdf.generic import ContentStream


def require(ok, reason):
    if not ok:
        raise ValueError(reason)


def occurrences(node):
    if isinstance(node, dict):
        if node.get('kind') in ('math_vector', 'math_vector_block', 'figure'):
            yield node
        for key in ('blocks', 'children'):
            for child in node.get(key, []):
                yield from occurrences(child)


def verify(job, pdf):
    package_bytes = (job/'document-package.json').read_bytes()
    package = json.loads(package_bytes)
    inventory = json.loads((job/'probe-inventory.json').read_bytes())
    require(hashlib.sha256(package_bytes).hexdigest() == inventory['package_sha256'], 'package changed since generation')
    expected = list(occurrences(package['document']))
    require(len(expected) == inventory['placements'], 'source placement count')
    images = package['resources']['images']
    require(len(images) == 5000, '5000 declarations')
    require({n['image_id'] for n in expected} == set(range(5000)), 'every declaration must be placed')
    reader = PdfReader(pdf, strict=True)
    root = reader.trailer['/Root']['/StructTreeRoot']
    nums = root['/ParentTree']['/Nums']
    parents = dict(zip(map(int, nums[::2]), nums[1::2]))
    index = 0
    content_to_object, object_to_content = {}, {}
    form_objects, raster_objects, observed = set(), set(), set()
    extracted = []
    for page_index, page in enumerate(reader.pages):
        parent_key = int(page['/StructParents'])
        array = parents[parent_key].get_object()
        stack, current, page_groups = [], None, 0
        for args, operator in ContentStream(page.get_contents(), reader).operations:
            if operator == b'BDC':
                props = args[1]
                outer = '/MCID' in props
                if outer:
                    require(current is None, 'nested MCID')
                    current = {'mcid': int(props['/MCID']), 'role': str(args[0]), 'text': [], 'paint': []}
                if '/ActualText' in props:
                    require(current is not None, 'unowned replacement text')
                    current['text'].append(str(props['/ActualText']))
                stack.append(outer)
            elif operator == b'BMC':
                stack.append(False)
            elif operator == b'Do':
                require(current is not None, 'untagged source paint')
                ref = page['/Resources']['/XObject'].raw_get(args[0])
                current['paint'].append(ref)
            elif operator == b'EMC':
                require(bool(stack), 'unbalanced marked content')
                if not stack.pop():
                    continue
                require(index < len(expected), 'extra paint group')
                want = expected[index]
                image = images[want['image_id']]
                vector = want['kind'] != 'figure'
                require(current['mcid'] == page_groups, 'dense MCIDs')
                require(current['role'] == ('/Formula' if vector else '/Figure'), 'source-order role')
                require(current['text'] == ([want['actual_text'] or want['alt']] if vector else []), 'source-order occurrence text')
                require(len(current['paint']) == 1, 'exactly one top-level image paint')
                ref = current['paint'][0]
                obj = ref.get_object()
                key = (ref.idnum, ref.generation)
                content = image['expected_sha256']
                require(content_to_object.setdefault(content, key) == key, 'alias must share XObject')
                require(object_to_content.setdefault(key, content) == content, 'distinct geometry must not collapse')
                require(obj['/Subtype'] == ('/Form' if vector else '/Image'), 'XObject subtype')
                if vector:
                    require('/ActualText' not in obj and '/Alt' not in obj and '/StructParent' not in obj, 'shared Form semantics')
                    box = list(map(float, obj['/BBox']))
                    viewport = want['metrics']['viewport']
                    require(len(box) == 4 and box[:2] == [0, 0], 'Form BBox origin')
                    require(abs(box[2]-viewport['width']/65536) <= 0.000001 and abs(box[3]-viewport['height']/65536) <= 0.000001, 'Form BBox dimensions')
                    form_objects.add(key)
                    extracted.append(want['actual_text'] or want['alt'])
                else:
                    require(obj['/Width'] == obj['/Height'] == 2, 'raster dimensions')
                    raster_objects.add(key)
                node = array[current['mcid']].get_object()
                require(node['/S'] == current['role'] and str(node['/Alt']) == want['alt'], 'ParentTree occurrence semantics')
                require((parent_key, current['mcid']) not in observed, 'duplicate MCID')
                observed.add((parent_key, current['mcid']))
                page_groups += 1
                index += 1
                current = None
        require(not stack and current is None, 'unclosed marked content')
        require(len(array) == page_groups, 'ParentTree group count')
    require(index == len(expected), 'missing occurrence paint')
    require(len(content_to_object) == inventory['distinct_resources'], 'all distinct resources used')
    for command in (["pdftotext", "-enc", "UTF-8", "-raw", str(pdf), "-"],
                    ["mutool", "draw", "-q", "-F", "txt", str(pdf)]):
        text = subprocess.run(command, check=True, capture_output=True).stdout.decode('utf-8')
        require(''.join(text.split()) == ''.join(''.join(extracted).split()), f"full occurrence extraction: {command[0]}")
    return {'scope': 'scale-probe-only', 'case': inventory['case'], 'pdf_sha256': hashlib.sha256(pdf.read_bytes()).hexdigest(),
            'pages': len(reader.pages), 'declarations': 5000, 'placements': index,
            'forms': len(form_objects), 'raster_xobjects': len(raster_objects), 'mcids': len(observed),
            'extractors': ['Poppler', 'MuPDF']}


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('job', type=Path)
    parser.add_argument('pdf', type=Path)
    args = parser.parse_args()
    print(json.dumps(verify(args.job, args.pdf), indent=2))
